#!/bin/sh
#//*========================================================================
#// keyer
#//
#// keyer [speed wpm]}
#//
#// Iambic keyer for the Raspberry Pi.
#// See accompanying README file for a description on how to use this code.
#// License:
#//   This program is free software: you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation, either version 2 of the License, or
#//   (at your option) any later version.
#//
#//   This program is distributed in the hope that it will be useful,
#//   but WITHOUT ANY WARRANTY; without even the implied warranty of
#//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#//   GNU General Public License for more details.
#//
#//   You should have received a copy of the GNU General Public License
#//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#//*========================================================================
#// lu7did: initial load
#*----------------------------------------------------------------------------
#* Initialization
#* DO NOT RUN EITHER AS A rc.local script nor as a systemd controlled service
#*----------------------------------------------------------------------------
#* Environment setup
#-----------------------------------------------------------------------------
DPATH="/home/pi/iambic-keyer"
cd $DPATH
export `dbus-launch | grep ADDRESS`
export `dbus-launch | grep PID`
trap 'echo Terminating...' INT

#*-----------------------------------------------------------------------------
#* Load jackd server as a background process
#*-----------------------------------------------------------------------------
jackd -P70 -p16 -t2000 -dalsa -dhw:1,0 -p512 -n4 -r48000 -s 2> /dev/null >> keyer.log &
PID=$!

#*-----------------------------------------------------------------------------
#* Load iambic
#*-----------------------------------------------------------------------------
./iambic -s $1 -m 2 2> /dev/null 

#*-----------------------------------------------------------------------------
#* Terminate
#*-----------------------------------------------------------------------------
sudo kill $PID 2>&1 | tee -a keyer.log
sudo pkill jackd 2>&1 | tee -a keyer.log
echo "********************************************"
echo "*             Finished iambic-keyer        *"
echo "********************************************"

